@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.hermitowo.advancedtfctech.compat.jei;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;