modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "advancedtfctech"
version = "${file.jarVersion}"
displayName = "Advanced TFC Tech"
authors = "HermitOwO"
description = '''

'''

[[dependencies.advancedtfctech]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.advancedtfctech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.advancedtfctech]]
modId = "tfc"
mandatory = true
versionRange = "[2.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.advancedtfctech]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[1.18.2-8.3.1-157,)"
ordering = "NONE"
side = "BOTH"
